version: '3'
services:
  customer-portal:
    build: ./Webanwendung
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - LOGGING_LEVEL=DEBUG
      - FLASK_DEBUG=True
    networks:
      - secbydesign


  # metering-point-operator:
  #   build: ./Anwendung
  #   depends_on:
  #     - customer-portal
  #   networks:
  #     - secbydesign

  # electricity-meter:
  #   build: ./Electricity-Meter
  #   deploy:
  #     replicas: 3
  #   depends_on:
  #     - metering-point-operator
  #   networks:
  #     - secbydesign

networks:
  secbydesign:
    driver: bridge