version: '3'
services:
  customer-portal:
    build: ./Customer-Portal
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - LOGGING_LEVEL=DEBUG
      - FLASK_DEBUG=True
    networks:
      - secbydesign

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file: ./mongodb.env
    networks:
      - secbydesign

  # metering-point-operator:
  #   build: ./Metering-Point-Operator
  #   depends_on:
  #     - customer-portal
  #   networks:
  #     - secbydesign

  # electricity-meter:
  #   build: ./Electricity-Meter
  #   deploy:
  #     replicas: 3
  #   depends_on:
  #     - metering-point-operator
  #   networks:
  #     - secbydesign

networks:
  secbydesign:
    driver: bridge