version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mounting nginx configuration file
      - ./certs:/etc/nginx/certs           # Mounting certificates
    depends_on:
      - customer-portal
      - metering-point-operator
    networks:
      - secbydesign

  customer-portal:
    build: ./Customer-Portal
    restart: unless-stopped
    environment:
      - SECRET_CP_MPO=65432109876543210
      - LOGGING_LEVEL=DEBUG
      - FLASK_DEBUG=False
      - LOCALDB=False
    networks:
      - secbydesign

  metering-point-operator:
    build:
      context: ./
      dockerfile: ./Metering-Point-Operator/Dockerfile
    restart: unless-stopped
    depends_on:
      - customer-portal
    environment:
      - SECRET_CP_MPO=65432109876543210
      - SECRET_MPO_EM=01234567890123456
      - LOGGING_LEVEL=DEBUG
      - FLASK_DEBUG=False
      - LOCALDB=False
    networks:
      - secbydesign

  electricity-meter:
    build: ./Electricity-Meter
    restart: unless-stopped
    deploy:
      replicas: 1 # Change according to the number of meters
    depends_on:
      - metering-point-operator
    ports: #TESTING ONLY
      - "5000:5000"
    environment:
      - SECRET_MPO_EM=01234567890123456
      - LOGGING_LEVEL=DEBUG
      - FLASK_DEBUG=False
    networks:
      - secbydesign

networks:
  secbydesign:
    driver: bridge