version: '3'
services:
  web:
    build: ./Webanwendung
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - secbydesign
  # app:
  #   build: ./Anwendung
  #   depends_on:
  #     - web
  #   networks:
  #     - secbydesign

  # em:
  #   build: ./Electricity-Meter
  #   deploy:
  #     replicas: 3
  #   depends_on:
  #     - app
  #   networks:
  #     - secbydesign

networks:
  secbydesign:
    driver: bridge
  # web-backend:
