version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "443:443"
      # - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mounting nginx configuration file
      - ./certs:/etc/nginx/certs           # Mounting certificates
    depends_on:
      - customer-portal
#      - metering-point-operator
    networks:
      - secbydesign

  customer-portal:
    build: ./Customer-Portal
    restart: unless-stopped
    environment:
      - LOGGING_LEVEL=DEBUG
      - FLASK_DEBUG=False
      - LOCALDB=False
    networks:
      - secbydesign

  # metering-point-operator:
  #   build: ./Metering-Point-Operator
  #   depends_on:
  #     - customer-portal
  #   networks:
  #     - secbydesign

  # electricity-meter:
  #   build: ./Electricity-Meter
  #   deploy:
  #     replicas: 3
  #   depends_on:
  #     - metering-point-operator
  #   networks:
  #     - secbydesign

networks:
  secbydesign:
    driver: bridge