swagger: '2.0'
info:
  version: v1
  title: DILLIGAF (Security-by-Design)
  description: Web-app API
host: localhost:5000
schemes:
  - https
paths:
  /:
    get:
      summary: GET index.html
      responses:
        '200':
          description: Returned on success.
  /register:
    get:
      summary: GET register.html
      responses:
        '200':
          description: Returned on success.
    post:
      summary: Register a user
      description: Register a user with username and password in the user db.
      consumes:
        - multipart/form-data
      parameters:
        - name: email
          in: formData
          description: User's email address
          required: true
          type: string
        - name: username
          in: formData
          description: User's username
          required: true
          type: string
        - name: password
          in: formData
          description: User's password
          required: true
          type: string
        - name: password2
          in: formData
          description: User's password
          required: true
          type: string
      responses:
        '200':
          description: Returned on success. A user has been successfully created.
          schema:
            type: object
        '500':
          description: Internal server error
  /login:
    get:
      summary: GET login.html
      responses:
        '200':
          description: Returned on success.
    post:
      summary: Login a user
      description: Login a user with username and password and get the JWT Token for authorization.
      consumes:
        - multipart/form-data
      parameters:
        - name: username
          in: formData
          description: User's username
          required: true
          type: string
        - name: password
          in: formData
          description: User's password
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '500':
          description: Internal server error
  /register/2fa:
    get:
      summary: GET register_2fa.html (only with valid JWT)
      responses:
        '200':
          description: Returned on success.
    post:
      summary: Register your 2fa
      description: Register the 2fa on the currently logged in user by verifying the otp token from the provided secret in the GET-Request 
      consumes:
        - multipart/form-data
      parameters:
        - name: otp
          in: formData
          description: User's otp generated by provided 2fa secret
          required: true
          type: integer
      responses:
        '200':
          description: Returned on success. A user 2fa has been successfully added.
          schema:
            type: object
        '500':
          description: Internal server error
  /login/2fa:
    get:
      summary: GET login_2fa.html (only with valid JWT)
      responses:
        '200':
          description: Returned on success.
    post:
      summary: Login with 2fa
      description: Login a user with the 2fa otp. Grants a new JWT Token with a 2fa timestamp for verification.
      consumes:
        - multipart/form-data
      parameters:
        - name: otp
          in: formData
          description: User's otp generated by provided 2fa secret
          required: true
          type: integer
      responses:
        '200':
          description: OK
          schema:
            type: object
        '500':
          description: Internal server error
  /logout:
    get:
      summary: Unsets the current JWT Token (only accessible with valid JWT)
      responses:
        '200':
          description: Returned on success.
          
  /create-contract:
    post:
      summary: Create a new contract
      description: Creates a new contract based on the input by the user.
      consumes:
        - multipart/form-data
      parameters:
        - name: coming-soon
          in: formData
          description: coming-soon
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '500':
          description: Internal server error
            
  /dashboard/:
    get:
      summary: GET register.html
      description: The Dashboard can only be accessed with a valid JWT Token and 2fa timestamp.
      responses:
        '200':
          description: Returned on success.